### ISSUE TITLE
it failed when migrating this project 

### ISSUE THREAD

**Issue by woshidama323** [provable-things/truffle-starter#1]
could you help to have a check it  ? is it a bug ?

version 
truffle(development)> version
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)

command ：
truffle migrate 

error log-------------------------
Using network 'development'.

Running migration: 1_deploy_contracts.js
  Deploying DieselPrice...
  ... 0x2e8cf448a0a3bd942e392c2c355c2ed123883b81281945cb2fbc28e5941f1a19
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
truffle(development)>   Deploying YoutubeViews...
  ... 0xc37a1903640aee414701aa107c3fd62a76b0bcb327b3635ef01751f6401336c5
  Deploying usingOraclize...
  ... 0x27076568db5dc59cac993f88a27f3cb2cfeedbfd72feb8119d3d8ac506eee1cf
  usingOraclize: 0xfcf91201bc7d98793c9180d70dab4b0ad27b7c39

**Comment by woshidama323** [comment]
i have changed the usingOraclize to the latest version from usingOraclize_0.5

**Comment by gskapka** [comment]
Hello @woshidama323 - sorry you were having issues! Glad you've switched to the new API version to solve them. 

Re the 0.4 version, it's because that Oraclize API is bound to solc versions no higher than 0.4.20, and truffle now comes bundled with the latest 0.4.24 compiler.

Changing the solc compiler that Truffle uses will soon be super easy (in the upcoming version 0.5), but for now alas we have to do it manually.  To do so, navigate to the directory where your truffle version is installed (be it locally, or globally) and run:

**`npm uninstall solc`**

Followed by:

**`npm install solc@0.4.20`**

Now you'll find the compiling and migrations work as expected.

We will update the Oraclize Truffle Box repo's readme to address the issue.
